spring.config.import=optional:file:.env[.properties]
spring.application.name=ChattyChat
spring.profiles.active=test

spring.docker.compose.enabled=false

# Database & JPA Configuration
spring.sql.init.mode=never
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Virtual Threads
spring.threads.virtual.enabled=true

# OAuth2 Providers
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

# Session & Reverse Proxy Configuration
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=${COOKIE_SECURE:true}
server.forward-headers-strategy=framework

# Documentation (Disabled in prod unless explicitly enabled)
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html