# config/deploy.yml
service: chattychat
image: ghcr.io/guijanson007/chattychat

servers:
  web:
    - 159.195.108.114

registry:
  server: ghcr.io
  username: guijanson007
  password:
    - KAMAL_REGISTRY_PASSWORD

  builder:
    arch: amd64

# Production Environment Variables injected by Kamal
env:
  clear:
    SPRING_PROFILES_ACTIVE: prod
    # chattychat-postgres is the internal Docker hostname Kamal gives to the database accessory
    SPRING_DATASOURCE_URL: jdbc:postgresql://chattychat-postgres:5432/chattychat_prod
    SPRING_DOCKER_COMPOSE_ENABLED: "false"
  secret:
    - DB_USERNAME
    - DB_PASSWORD

# PostgreSQL managed as a Kamal accessory on the VPS
accessories:
  postgres:
    image: postgres:16-alpine
    host: 159.195.108.114
    port: "127.0.0.1:5432:5432" # Bound locally so only internal network / SSH can reach it
    env:
      clear:
        POSTGRES_DB: chattychat_prod
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - postgres-data:/var/lib/postgresql/data